### ISSUE TITLE
DnDTabbedPane: Drag a tab and start moving it, the tab component disappears

### ISSUE THREAD

**Issue by rsfairman** [aterai/java-swing-tips#13]
This is not a problem with your class as written, but `SwingUtilities.paintComponent()` behaves in a way that can cause problems if small modifications are made.

I modified `DnDTabbedPane` so that the title of the tab is a `Component` and not a simple string. In my case, this `Component` consists of a `JLabel` and a `JButton`. 

In `initGlassPane()`, `SwingUtilities.paintComponent()` is used to create the ghost image to drag around. For reasons I do not understand (Swing internals), the call to `paintComponent()` seems to change the ownership of the tab's `Component` -- or that is my guess. The fix is to duplicate the result of the call to `getTabComponentAt(dragTabIndex)` and feed that duplicate to `paintComponent()`. Exactly how this duplication is done will depend depend on the contents of the situation, so I can't offer a general fix.

**Comment by aterai** [comment]
@rsfairman Thanks for the report.
The fix for this issue itself was already implemented in #11, but we have added a tab component and tab icon as a sample to verify that the tab drag image is displayed correctly.
