### ISSUE TITLE
素晴らしい。

### ISSUE THREAD

**Issue by koryovip** [aterai/java-swing-tips#6]
１０何年前から、Java Swing Tips をお世話になっております。

参加していたプロジェクトで Swing を使用することになり、ネットで検索したら　https://ateraimemo.com/Swing.html
に辿り着きました。当時（今でも）Swing が人気がなく、ちゃんと Swing のことを紹介するサイトはあんまりなかったですが、そのまま実行できるサンプルコードまであるサイトには、本当に感動しました。
おかげさまでプロジェクトが無事終了しましたが、Swing に対し興味を持ちました。以来、ちょっとしたツールを作るなどの時には、必ず　Java Swing Tips　に来て、参考になるのもがないかと。来るたびに思うですが、Swing のことで１０何年も更新し続けるのは、本当に素晴らしいです！心から感謝しています。本当にありがとうございます。

Swing は本当に使える物なのに、全然人気がないですね。
私は Swing 大好きな、時々遊びに来ますので、どうか続けてください。

よろしくお願いします。

**Comment by aterai** [comment]
レポートありがとうございます。
Swingは個人的にもWidows 10やUbuntuで動作可能なアプリの作成などで色々使用しているので、まだまだ続けていきたいと考えています。
これからもよろしくお願いします。
